#!/usr/bin/env bash
# A script that will display information about subdomains, after configuring your domain zone so
# that the subdomain www points to your load-balancer IP (lb-01), and adding other subdomains.

query ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", $subdomain, $4, $5}'
}

for subdomain in "www" "lb-01" "web-01" "web-02" ; do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	query "$1" "$subdomain"
    fi
done
