#!/usr/bin/env bash
# A script that configures a new Ubuntu machine
# Ensure Nginx is present and listening on port 80
# Ensure when querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it returns a page that contains the string Hello World!

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw status
echo "Hello World!" | sudo tee -a /var/www/html/index.nginx-debian.html
sudo service nginx start
