#!/usr/bin/env bash
# A script that configures a new Ubuntu machine.
# Ensure redirection must be a “301 Moved Permanently”
# Use what you did with 1-install_nginx_web_server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	server_name _;

    root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

bash -c "echo -e '$CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
