#!/usr/bin/env bash
# A script that configures a new Ubuntu machine.
# Ensure redirection must be a “301 Moved Permanently”
# Use what you did with 1-install_nginx_web_server
CONFIG_FILE="/etc/nginx/sites-available/default"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/tty1
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > $CONFIG_FILE
sudo service nginx restart
