#!/usr/bin/env bash
# A script that configures a new Ubuntu machine.
# Ensure redirection must be a “301 Moved Permanently”
# Use what you did with 1-install_nginx_web_server

REDIR="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "30i $REDIR" /etc/nginx/sites-available/default
sudo service nginx restart
