#!/usr/bin/env bash
# A script that configures Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page
# Ensure the page returns an HTTP 404 error code
# Ensure the page contains the string "Ceci n'est pas une page"
# Use what you did with 3-redirection

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
