#!/usr/bin/env bash
# A script that configures a new Ubuntu machine. Starting by
# configuring HAproxy so that it send traffic to web-01 and web-02,
# distributing requests using a roundrobin algorithm,
# making sure that HAproxy can be managed via an init script and
# making sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo apt-get -y install haproxy
echo "web-01","web-02" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

CONFIG="\
frontend http-https-in
bind    *:80
bind    *:443

use_backend http_nginx_pool    if !{ ssl_fc }
use_backend https_nginx_pool   if { ssl_fc }

backend http_nginx_pool
    balance roundrobin
    mode http
    server nginx 3.238.111.241:80 check
    server nginx 3.238.120.131:80 check

backend https_nginx_pool
    balance roundrobin
    mode http
    server nginx 3.238.111.241:443 check
    server nginx 3.238.120.131:443 check
"

echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service nginx start
sudo service haproxy start
