#!/usr/bin/env bash
# A script that configures a new Ubuntu machine. Starting by
# configuring HAproxy so that it send traffic to web-01 and web-02,
# distributing requests using a roundrobin algorithm,
# making sure that HAproxy can be managed via an init script and
# making sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "web-01, web-02" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo apt-get -y install haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

CONFIG="\
frontend http_web *:80
    mode http
    bind *:80
    default_backend 22113-web
    
backend 22113-web
    balance roundrobin
    mode http
    server 22113-web-01 3.238.111.241:80 check
    server 22113-web-02 3.238.120.131:80 check
"

echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
