#!/usr/bin/env bash
# A script that configures Nginx(a server) to be running, and
# listening on port 80 of all the server’s active IPv4 IPs

sudo sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
sudo kill -1 nginx
