#!/usr/bin/env bash
# This script that displays the content of the file /etc/passwd.
# should only display:
# username
# user id
# Home directory path for the user
while IFS=: read -r user
do
    echo "$user" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
