#!/usr/bin/env bash
# A script that installs the ufw firewall and setups a few rules on web-01

sudo apt-get -y install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
